SET SCHEMA 'log515_cyga';

TRUNCATE TABLE acronym
RESTART IDENTITY;

INSERT INTO acronym(acronym, definition)
VALUES
  ('AA', 'alcooliques anonymes'),
  ('AG', 'assemblée générale'),
  ('FIQ', 'fédération des infirmières du québec'),
  ('HLM', 'habitation loyer modique'),
  ('MTQ', 'ministère du transport du québec'),
  ('OSBL', 'organisme sans but lucratif'),
  ('RH', 'ressources humaines'),
  ('PMBOK', 'project management book of knowledge'),
  ('ITIL', 'information technology infrastructure library'),
  ('ARP', 'address resolution protocol'),
  ('FC', 'forces canadiennes'),
  ('MRC', 'municipalité régionale de comté'),
  ('QG', 'quartier général'),
  ('ADIDAS', 'all day i dream about sex'),
  ('ABS', 'anti-lock braking system'),
  ('ADN', 'acide désoxyribonucléique'),
  ('BD', 'bande dessinée'),
  ('BCBG', 'bon chic bon genre'),
  ('CIA', 'central intelligence agency'),
  ('FBI', 'federal bureau of investigation'),
  ('CV', 'curriculum vitae'),
  ('DJ', 'disk jockey'),
  ('GPS', 'global positioning system'),
  ('KO', 'knock out'),
  ('MSF', 'médecins sans frontières'),
  ('OGM', 'organisme génétiquement modifié'),
  ('OMS', 'organisation mondiale de la santé'),
  ('OVNI', 'objet volant non identifié'),
  ('QI', 'quotient intellectuel'),
  ('SDF', 'sans domicile fixe'),
  ('SMS', 'short message service'),
  ('SIDA', 'syndrome d’immuno-déficience acquise'),
  ('TGV', 'train à grande vitesse'),
  ('VIP', 'very important person'),
  ('VTT', 'véhicule tout terrain'),
  ('TVA', 'taxe sur la valeur ajoutée'),
  ('TVQ', 'taxe de vente du Québec'),
  ('OIQ', 'ordre des ingénieurs du Québec'),
  ('DEC', 'diplôme d''études collégiales'),
  ('ASSS', 'agence de la santé et des services sociaux'),
  ('ARC', 'agence de revenu Canada'),
  ('AFP', 'attestation de formation professionnelle'),
  ('SODEC', 'société de développement des entreprises culturelles'),
  ('IEEE', 'institute of electrical and electronics engineers'),
  ('ASCII', 'american standard code for information interchange'),
  ('NAS', 'numéro d’assurance sociale'),
  ('FAL', 'fusil automatique léger'),
  ('OLED', 'organic light-emitting diode'),
  ('LED', 'light-emitting diode'),
  ('FLOPS', 'floating point operations per second'),
  ('CMS', 'content management system'),
  ('GIF', 'graphics interchange format'),
  ('ISO', 'international organization for standardization'),
  ('RAM', 'random access memory'),
  ('CEGEP', 'collège d’enseignement général et professionnel'),
  ('CAN', 'controller area network'),
  ('RIP', 'routing information protocol'),
  ('CERN', 'conseil européen pour la recherche nucléaire'),
  ('MAC', 'media access control'),
  ('SIM', 'subscriber identity module'),
  ('DOS', 'disk operating system'),
  ('ATM', 'automated teller machines'),
  ('ROM', 'read-only memory'),
  ('SATA', 'serial advanced technology attachment'),
  ('ALENA', 'accord de libre-échange nord-américain');

COMMIT;